config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/index'

  get 'pages/search'

  get 'pages/info'

  get 'pages/find_products'
  resources :categories

  resources :products do
    resources :comments, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'

  }

  devise_scope :user do
    patch 'users/upgrade', to: 'user/registrations#upgrade'
  end

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    if user.present?
      can :create, Product
      can [:edit, :destroy], Product, user_id: user.id
      can :create, Comment
      can [:destroy], Comment, user_id: user.id
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :product
  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	belongs_to :brand

	has_many :comments
	
	belongs_to :user

	has_many :photos, dependent: :destroy

	has_many :specs, dependent: :destroy
	has_many :tags, through: :specs, dependent: :destroy

end

app/models/spec.rb
class Spec < ApplicationRecord
  belongs_to :product
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :specs
	has_many :products, through: :spec
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products
  has_many :comments
  enum role: [:user, :shop, :admin, :guest]
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
      @product = Product.find(params[:product_id])
      @user = current_user

      @comment = Comment.new(comment_params)

      @comment.product = @product
      @comment.user = current_user

      @comment.save
  end

  def destroy
      @product = Product.find(params[:product_id])
      @comment = Comment.find(params[:id])

      @comment.destroy
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@products = Product.order('created_at DESC LIMIT 20')
  end

  def search
  	@products = Product.all

  	@cantidades = []
  	Category.all.each do |category|
  		@cantidades << category.products.size
  	end

  end

  def info
  end

  def find_products
    if params[:buscar].present?
      @products = Product.where('name like ?', "%#{params[:buscar]}%")
      respond_to do |format|
        format.js
      end
    else
      @products = Product.order('created_at DESC LIMIT 5')
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def create
	    @product = Product.find(params[:product_id])
	    @photo = Photo.new(photo_params)
	    @photo.product = @product
	    if @photo.save
	      redirect_to edit_product_path(@product)
	    else
	      redirect_to edit_product_path(@product), notice: 'error'
	    end
	end

	def destroy
	    @product = Product.find(params[:product_id])
	    @photo = Photo.find(params[:id])

	    @photo.destroy
	    redirect_to edit_product_path(@product)
	end

	private
	
    def photo_params
      params.require(:photo).permit(:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurfinApp</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

  	<%= render 'shared/navbar' %>

    <%= yield %>


  </body>
</html>

app/views/pages/find_products.js.erb
if (<%= @products.size %> > 0){
  $('#products').html("<%= j render @products %>");
}else {
  $('#products').html("<h5> No se encontró tu producto :C </h5>");
}

app/views/pages/index.html.erb
<div class="container-fluid ">
	<div class="row pt-5">
		<div class="col-md-3">
			<%= render 'shared/widgetCategorias' %>

		</div>
		<div class="col-md-6">
			<div class="row d-flex align-items-stretch" id="products">


					<% @products.each do |product| %>
						<div class="card m-1" style="width: 13rem;">

						  <div class="card-img-box" style="background-image:url(<%= asset_path 'exampleGuitar.jpg' %>)">
							</div>

						  <div class="card-body d-flex align-items-end">
						  	<div class="w-100">
						  		<h5 class="card-title text-center"><%= product.name %></h5>

							    <p class="card-text">$<%= product.price %></p>

							    	<%= link_to product do %>

											<div class="text-right card-link btn d-flex">
												<h5 class="text-right">
													Go
													<i class="fas fa-angle-right"></i>
												</h5>
											</div>


									<% end %>



						  	</div>

						  </div>
						</div>
					<% end %>


			</div>
		</div>
		<div class="col-md-3">

		</div>
	</div>
</div>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>

app/views/pages/search.html.erb
<div class="container-fluid">
	<div class="skin">
		<div class="row">
			<div class="col-md-3">
				<ul class="category-list boxed">
					<% i = 0 %>
					<% Category.all.each do |category| %>
						<li>
							<a class="" href="#">
								<%= category.name %>
								<p class='contador'>
									(<%= @cantidades[i] %>)
								</p>
								<% i += 1 %>	
							</a>
							
						</li>
			        <% end %>

				</ul>
				
			</div>

			<div class="col-md-9">
				<div class="row gap">
					
						<% @products.each do |product| %>
							<div class="card m-1 elegant" style="width: 12rem;">
							  <img class="card-img-top" src="https://picsum.photos/200/200" alt="Card image cap">
							  <div class="card-body">
							    <h5 class="card-title"><%= product.name %></h5>
							    
							    <p class="card-text"><%= product.price %></p>
							    <%= link_to 'Show', product %>
							  </div>
							</div>
						<% end %>
					
					
				</div>
						
			</div>

			
		</div>
	</div>
	
</div>

app/views/shared/_comment_element.html.erb
<li id="comment<%= @comment.id %>"><%= @comment.content %> <%= link_to 'Borrar', product_comment_path(@product,@comment), data: {method: :delete, remote: true}, class: 'btn btn-danger' if can? :destroy, @comment %></li>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <a class="navbar-brand" href="<%= root_path %>">
  <figure class="figure">
    <%= image_tag 'logo-01.png', class: 'figure-img img-fluid logo' %>
  </figure>

  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">

      </li>
    </ul>


    <div class="dropdown mr-2">

      <button class="btn btn-info btn-categories dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Categorías
      </button>

      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <% Category.all.each do |category| %>
          <a class="dropdown-item" href="#"><%= category.name %></a>
        <% end %>
      </div>

    </div>


    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" id="buscar" type="search" placeholder="Buscar..." aria-label="Search">
      <button class="btn btn-info btn-search my-2 my-sm-0" type="submit">Buscar</button>
    </form>

    <ul class="navbar-nav ml-auto">
      <% if current_user.present? %>
        <li class="nav-item active btn btn-sale">

          <%= link_to new_product_path, class: 'nav-link' do %>
            <p class="m-0">Vender<i class="fas fa-box ml-1"></i></p>

          <% end %>


        </li>

        <li class="nav-item active pl-3">
          <%= link_to edit_user_registration_path do %>
            <h3 class='nav-link disable' ><i class="far fa-user-circle"></i></h3>
          <% end %>
        </li>
        <li class="nav-item active">

          <%= link_to destroy_user_session_path, method: :delete  do %>
            <i class="far fa-times-circle"></i>
          <% end %>
        </li>
      <% else %>
          <li class="nav-item active">
            <%= link_to 'Registrate', new_user_registration_path, class: 'nav-link' %>
          </li>

          <li class="nav-item active">
            <%= link_to 'Iniciar Sesión', new_user_session_path, class: 'nav-link' %>
          </li>
      <% end %>
    </ul>
  </div>
</nav>

<script type="text/javascript">
  $('#buscar').keyup(function () {
    var q = $(this).val()
    $.ajax({
      url: '<%= pages_find_products_path %>',
      type: 'GET',
      data: {
        buscar: q
      }
    })
    .done(function() {
      console.log("success");
    })
    .fail(function() {
      console.log("error");
    })
    .always(function() {
      console.log("complete");
    });

  });
</script>

app/views/shared/_shopProfile.html.erb
<h1> ERES UNA TIENDA</h1>
<%= form_with model: current_user, url: user_registration_path, local: true do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :profile_photo %>
  <%= f.text_field :profile_pic %>

  <%= f.label :portada %>
  <%= f.text_field :banner_pic %>

  <%= f.label :dirección %>
  <%= f.text_field :address %>

  <%= f.label :descripción %>
  <%= f.label :description %>

  <%= f.submit %>
<% end %>
<%
=begin
tabla usuario
t.string "name"
t.string "phone"
t.string "profile_pic"
t.string "banner_pic"
t.string "address"
t.text "description"
=end
%>

app/views/shared/_userProfile.html.erb
<%= form_with model: current_user, url: user_registration_path, local: true do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :profile_photo %>
  <%= f.text_field :profile_pic %>

  <%= f.submit %>
<% end %>

<%= link_to 'Conviertete en tienda', users_upgrade_path, method: :patch, class:'btn btn-success' %>
<%
=begin
tabla usuario
t.string "name"
t.string "phone"
t.string "profile_pic"
t.string "banner_pic"
t.string "address"
t.text "description"
=end
%>

app/views/shared/_widgetCategorias.html.erb
			<div class="pl-3">

				<ul class="widget-categorias boxed-style">
					<h3 class="widget-title ">Categorias</h3>
					 <% Category.all.each do |category| %>

			          
			          
			          		<%= link_to category do %>
			          			<li><%= category.name   %></li>
			          		<% end %>
			          	
			         

			        <% end %>
				</ul>
			</div>

app/views/shared/_widgetShop.html.erb
<%= @product.user.address %>
<%= @product.user.email %>

app/views/shared/_widgetUser.html.erb
<div class="widget-user-info">
	<div class="user-profile-photo text-center">
		<h2>
			<i class="fas fa-user-circle"></i>
		</h2>
		
	</div>
	<h5 class="text-center">
		<%= @product.user.name %>
	</h5>
	<h6 class="text-center">
		<i class="fas fa-envelope-open pr-2"></i><%= @product.user.email %>
	</h6>
	<h6 class="text-center">
		<i class="fas fa-phone pr-2"></i><%= @product.user.phone %>
	</h6>
	
	
	
</div>